name: lancache-monolithic
description: |
      This docker container provides a caching proxy server for game download content. For any network with more than one PC gamer in connected this will drastically reduce internet bandwidth consumption.
version: v1.0.0
category: Caching
maintainer: Jessica Smith, Robin Lewis, Brian Wojtczak, Jason Rivers, James Kinsman
license: MIT License
projectURL: "https://lancache.net"

